name: 'Ngekos CD'
author: 'Bakunya | Kirisaki Rem'
inputs:
  host:
    description: 'ssh host'
  port:
    description: 'ssh port'
  key:
    description: 'ssh private key'

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2