name: Ngekos CD
author: Bakunya
inputs:
  host:
    description: 'ssh host'
  port:
    description: 'ssh port'
    default: 22
  username:
    description: 'ssh username'
  key:
    description: 'ssh key'
  script:
    description: 'execute commands'